DROP TABLE IF EXISTS participation_requests CASCADE;
CREATE TABLE participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL,
    created      TIMESTAMP   NOT NULL
);