DROP TABLE IF EXISTS events CASCADE;
CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000)    NOT NULL,
    category_id        BIGINT           NOT NULL,
    created_on         TIMESTAMP        NOT NULL,
    description        VARCHAR(7000)    NOT NULL,
    event_date         TIMESTAMP        NOT NULL,
    initiator_id       BIGINT           NOT NULL,
    lat                DOUBLE PRECISION NOT NULL,
    lon                DOUBLE PRECISION NOT NULL,
    paid               BOOLEAN DEFAULT FALSE,
    participant_limit  INT     DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN DEFAULT TRUE,
    state              VARCHAR(20)      NOT NULL,
    title              VARCHAR(120)     NOT NULL
);