DROP TABLE IF EXISTS compilations CASCADE;
CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS compilation_events CASCADE;
CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);