DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    activated boolean NOT NULL
);

DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(50) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS events CASCADE;
CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000)    NOT NULL,
    category_id        BIGINT           NOT NULL REFERENCES categories (id),
    created_on         TIMESTAMP        NOT NULL,
    description        VARCHAR(7000)    NOT NULL,
    event_date         TIMESTAMP        NOT NULL,
    initiator_id       BIGINT           NOT NULL REFERENCES users (id),
    lat                DOUBLE PRECISION NOT NULL,
    lon                DOUBLE PRECISION NOT NULL,
    paid               BOOLEAN DEFAULT FALSE,
    participant_limit  INT     DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN DEFAULT TRUE,
    state              VARCHAR(20)      NOT NULL,
    title              VARCHAR(120)     NOT NULL
);

DROP TABLE IF EXISTS participation_requests CASCADE;
CREATE TABLE participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    requester_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(20) NOT NULL,
    created      TIMESTAMP   NOT NULL
);

DROP TABLE IF EXISTS compilations CASCADE;
CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS compilation_events CASCADE;
CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);
